### ISSUE TITLE
git init

### ISSUE THREAD

**Issue by theadeyemiolayinka** [theadeyemiolayinka/python-scripts#1]
**First Issue:**
Create an Hello World! Project following the [contribution guidelines.](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)

**Comment by rishabhknowss** [comment]
Hey can you assign me the issue under hacktoberfest label?

**Comment by theadeyemiolayinka** [comment]
No Problem!
Feel free to create new issues and add more projects.

**Comment by theadeyemiolayinka** [comment]
@rishabhknowss
You haven't submitted a PR yet.
