### ISSUE TITLE
ValorantStats using Valorant API

### ISSUE THREAD

**Issue by jonascarvalh** [theadeyemiolayinka/python-scripts#113]
Hello everything is fine? I would like to create an example of using APIs with Python, and to show my love for the game.
I hope you accept and consider it for hacktoberfest.

**Comment by theadeyemiolayinka** [comment]
Ok @jonascarvalh. Go ahead.

**Comment by jonascarvalh** [comment]
#114 All done ✅

**Comment by theadeyemiolayinka** [comment]
The project was reviewed and merged. Thank you @jonascarvalh 
Feel free to star this repo and add more projects.

**Comment by jonascarvalh** [comment]
Starred 🌟
