### ISSUE TITLE
Tic Tac Toe Game in Python

### ISSUE THREAD

**Issue by asryan11** [theadeyemiolayinka/python-scripts#118]

**Comment by asryan11** [comment]
@theadeyemiolayinka Can you assign me this issue?  This contribution is for Hacktoberfest can you also add that label too.

**Comment by theadeyemiolayinka** [comment]
Go ahead @asryan11

**Comment by theadeyemiolayinka** [comment]
The project was reviewed and merged. Thank you @asryan11 
Feel free to star this repo and add more projects.
