### ISSUE TITLE
Hacktoberfest Python Scripts Contributions. 

### ISSUE THREAD

**Issue by theadeyemiolayinka** [theadeyemiolayinka/python-scripts#133]
You can add any of your hacktoberfest python projects following the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md).

**Comment by Jacintomuambumba** [comment]
we are working on this issue, team CoDev
#aoscode
#aosccode

**Comment by elsa-linu** [comment]
hey, can i work on this issue?

**Comment by theadeyemiolayinka** [comment]
Go ahead, @elsa-linu @Jacintomuambumba

**Comment by gh-adithya** [comment]
Hi! I would like to work on this issue as my first contribution.
