### ISSUE TITLE
Add an Expense Tracker

### ISSUE THREAD

**Issue by JuanitaCathy** [theadeyemiolayinka/python-scripts#134]
A Python script for tracking expenses.
This script allows users to record their expenses which makes tracking the expense easy. 
The script uses a CSV file to store the data and the user can add, view and exit from the app.

**Comment by JuanitaCathy** [comment]
@theadeyemiolayinka Please assign it to me under hacktoberfest, thank you!

**Comment by theadeyemiolayinka** [comment]
Go ahead, @JuanitaCathy

**Comment by JuanitaCathy** [comment]
@theadeyemiolayinka do i create a separate folder called python scripts or do it inside src?

**Comment by theadeyemiolayinka** [comment]
All contributors should add their scripts inside a folder named after their username in the src folder and each project should have its own folder in the contributor's folder.

You can refer to the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md) for further explanation.

**Comment by JuanitaCathy** [comment]
@theadeyemiolayinka Please review and let me know if there are any changes.
