### ISSUE TITLE
Discord bot script

### ISSUE THREAD

**Issue by navdiya-nikunj** [theadeyemiolayinka/python-scripts#155]
I want to add discord bot python script to this repo. Can you assign this issue to me? @theadeyemiolayinka 

I will add the python script for simple discord bot. Please add hacktoberfest label to it to give value to my contribution

**Comment by theadeyemiolayinka** [comment]
Go ahead, @navdiya-nikunj

**Comment by theadeyemiolayinka** [comment]
Howdy @navdiya-nikunj

**Comment by navdiya-nikunj** [comment]
It's almost done I'll create a pr by tomorrow
