### ISSUE TITLE
JSON to CSV

### ISSUE THREAD

**Issue by JuanitaCathy** [theadeyemiolayinka/python-scripts#174]
A python script that can be used to convert json to csv.

**Comment by theadeyemiolayinka** [comment]
Go ahead, Juanita.

**Comment by JuanitaCathy** [comment]
For some reason, I'm not able to create a PR :( @theadeyemiolayinka 
![image](https://github.com/theadeyemiolayinka/python-scripts/assets/114871036/59089a51-9d59-4934-b196-596f9b597888)

**Comment by theadeyemiolayinka** [comment]
Can

**Comment by JuanitaCathy** [comment]
> Can you please try again and reply the error message if the issue persists?
 
It works now

**Comment by theadeyemiolayinka** [comment]
Howdy @JuanitaCathy
