### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by lukman155** [theadeyemiolayinka/python-scripts#180]
I want to create a Todo list, can you assign this to me?

**Comment by theadeyemiolayinka** [comment]
Go ahead, @lukman155

**Comment by chiku011** [comment]
can you assign this issue to me

**Comment by theadeyemiolayinka** [comment]
Go ahead, @chiku011

**Comment by chiku011** [comment]
hii @theadeyemiolayinka plz check my merge request and tell me if you want any changes in it
