### ISSUE TITLE
Reddit Bot 

### ISSUE THREAD

**Issue by Shreya111111** [theadeyemiolayinka/python-scripts#183]
This is a fairly simple concept as the program checks every comment in a selected subreddit and then replies to any comments that contain a predefined ‘trigger phrase’.

**Comment by Shreya111111** [comment]
/assign
Give this a hacktober tag

**Comment by Shreya111111** [comment]
@theadeyemiolayinka

**Comment by theadeyemiolayinka** [comment]
Go ahead, @Shreya111111
