### ISSUE TITLE
Hacktoberfest Python Projects

### ISSUE THREAD

**Issue by theadeyemiolayinka** [theadeyemiolayinka/python-scripts#2]
Add any of your hacktoberfest python projects following the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md).

**Comment by aman6969** [comment]
please assign this to me @theadeyemiolayinka

**Comment by theadeyemiolayinka** [comment]
@aman6969
You haven't submitted a PR yet.

**Comment by aman6969** [comment]
and your upload files is locked i tried to submit PR in that

**Comment by theadeyemiolayinka** [comment]
> and your upload files is locked i tried to submit PR in that

@aman6969
I do not understand what you mean, are you unable to create a PR?

**Comment by aman6969** [comment]
when i went to code section and trying to add file in it's showing adding and uploading files are locked @theadeyemiolayinka

**Comment by theadeyemiolayinka** [comment]
@aman6969 
Have you tried editing/uploading the files in your fork?

**Comment by aman6969** [comment]
i have forked and uploaded my folder inside scr folder please check once @theadeyemiolayinka

**Comment by aman6969** [comment]
i have created a game named it red ball @theadeyemiolayinka

**Comment by aman6969** [comment]
> @aman6969 Have you tried editing/uploading the files in your fork?

yes!!
@theadeyemiolayinka

**Comment by theadeyemiolayinka** [comment]
@aman6969 Okay, try creating a PR from your fork now.
If you still can't, could you please share a screenshot of your problem?

**Comment by aman6969** [comment]
okey @theadeyemiolayinka

**Comment by aman6969** [comment]
please check i have created PR @theadeyemiolayinka

**Comment by theadeyemiolayinka** [comment]
@aman6969 Good!
I left a review for you.

**Comment by theadeyemiolayinka** [comment]
@aman6969 Seems like you're using github web, I'll take care of the issue

**Comment by aman6969** [comment]
> @aman6969 Good! I left a review for you.
thankyou 
yes i saw your review i am doing it!!

**Comment by aman6969** [comment]
> @aman6969 Seems like you're using github web, I'll take care of the issue

yes!! @theadeyemiolayinka

**Comment by aman6969** [comment]
i have made one more game will you merge it may i send you pull request? @theadeyemiolayinka

**Comment by theadeyemiolayinka** [comment]
@aman6969 Yes, I'll make them for you.

**Comment by theadeyemiolayinka** [comment]
@aman6969 Create a new [issue](https://github.com/theadeyemiolayinka/python-scripts/issues/new) for your new game and make sure to follow the guidelines this time.

**Comment by aman6969** [comment]
> @aman6969 Yes, I'll make them for you.

thank you so much @theadeyemiolayinka

**Comment by aman6969** [comment]
> @aman6969 Create a new [issue](https://github.com/theadeyemiolayinka/python-scripts/issues/new) for your new game and make sure to follow the guidelines this time.

ok i will take care of that. @theadeyemiolayinka

**Comment by theadeyemiolayinka** [comment]
@aman6969 You're welcome.
Please learn how to use Github Desktop and git commands, it'll help your developer journey.
Fell free to star the repo.

**Comment by aman6969** [comment]
> @aman6969 You're welcome. Please learn how to use Github Desktop and git commands, it'll help your developer journey. Fell free to star the repo.

yes i am learning to use github desktop and git commands thankyou for your comments i have already stared the repo.
