### ISSUE TITLE
I want to add a personal voice assistant in python

### ISSUE THREAD

**Issue by sainikhitha-sayyaparaju** [theadeyemiolayinka/python-scripts#20]
This can perform various tasks such as telling jokes, send whatsapp messages, play songs from youtube, mark locations in maps and a lot more

**Comment by sainikhitha-sayyaparaju** [comment]
can you assign this to me?

**Comment by theadeyemiolayinka** [comment]
@sainikhitha-sayyaparaju  You're already assigned.
