### ISSUE TITLE
Add Python Projects

### ISSUE THREAD

**Issue by theadeyemiolayinka** [theadeyemiolayinka/python-scripts#3]
Add any Python project following the [contribution guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/d10d5beadbf0c8edba166eb18b30ba3438b4c221/contributing.md)

**Comment by banjaneyulu** [comment]
Hi @theadeyemiolayinka, I would like to add the python project here, please assign it to me

**Comment by yashsarnaik22** [comment]
hey can I add some of mine?
assign this to me

**Comment by theadeyemiolayinka** [comment]
@banjaneyulu @yashsarnaik22
Sure, you can also add other projects by creating an issue.

Feel free to star the repo.
