### ISSUE TITLE
Add Hacktoberfest Python Projects

### ISSUE THREAD

**Issue by theadeyemiolayinka** [theadeyemiolayinka/python-scripts#4]
Add your projects following the [contribution guide](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)

**Comment by richie-6789** [comment]
please assign this to me

**Comment by theadeyemiolayinka** [comment]
@richie-6789 
Create a new issue stating the project you wish to add.
Make sure to follow the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
Cheers!

**Comment by theadeyemiolayinka** [comment]
@siddhesh-coder 
I am yet to receive your PR.

**Comment by riya02002** [comment]
assign this to me plz

**Comment by theadeyemiolayinka** [comment]
@MSVelan 
Go ahead!
