### ISSUE TITLE
BlackJack Game

### ISSUE THREAD

**Issue by Money-20** [theadeyemiolayinka/python-scripts#43]
I want to create the  BlackJack Cards Game using python. It is a text-based terminal game which is a great starting point in creating games using python.

**Comment by theadeyemiolayinka** [comment]
Go ahead!

**Comment by richie-6789** [comment]
Hey, I would like to work on this using js.

**Comment by theadeyemiolayinka** [comment]
@richie-6789 
You can go ahead, but this is a python repo, so make sure you include at least a python file, even if it prints "Hello World!"
