### ISSUE TITLE
Quiz GUI using tkinter

### ISSUE THREAD

**Issue by Money-20** [theadeyemiolayinka/python-scripts#44]
I want to create a Quiz app using tkinter module in python which takes questions as input storing it internally to use those for the quiz.

**Comment by theadeyemiolayinka** [comment]
Go ahead!

**Comment by theadeyemiolayinka** [comment]
@Money-20
I am yet to receive a PR.

**Comment by Money-20** [comment]
I am working on it. I'll push it soon
