### ISSUE TITLE
A Coffee Machine program created using OOP

### ISSUE THREAD

**Issue by thisisamish** [theadeyemiolayinka/python-scripts#5]
I want to add a program that basically simulates how an automated coffee machine would work. What makes this project worth including in your repo is because it is written entirely using object oriented paradigm of programming and hence serves as a good example of how to write OOP programs.

**Comment by theadeyemiolayinka** [comment]
@thisisamish
Go ahead.

**Comment by theadeyemiolayinka** [comment]
@thisisamish

**Comment by thisisamish** [comment]
Hey @theadeyemiolayinka I am just finished with it. Will make a PR in an hour or so.

**Comment by thisisamish** [comment]
Hey @theadeyemiolayinka, I have made the PR. Please let me know if any changes are required.

**Comment by theadeyemiolayinka** [comment]
#58 has been merged,
Thanks man.
