### ISSUE TITLE
Python Hacktoberfest Contribution.

### ISSUE THREAD

**Issue by theadeyemiolayinka** [theadeyemiolayinka/python-scripts#57]
Feel free to add any python project following the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md).

**Comment by atharbeginner** [comment]
Hello @theadeyemiolayinka I want to create py script to send emails

**Comment by theadeyemiolayinka** [comment]
@atharbeginner Go ahead!
