### ISSUE TITLE
Budget Manager using Django

### ISSUE THREAD

**Issue by Money-20** [theadeyemiolayinka/python-scripts#63]
Budget Manger Web- Application developed using Django. It is a simple Transaction recorder possessing CRUD functionalities, USER authentication and much more.

**Comment by theadeyemiolayinka** [comment]
Go ahead!

**Comment by theadeyemiolayinka** [comment]
@Money-20 
I'm yet to receive a PR.

**Comment by Money-20** [comment]
I am working on it. I'll push it soon.

**Comment by theadeyemiolayinka** [comment]
@Money-20
Howdy?

**Comment by Money-20** [comment]
I guess it might take time because my laptop is broken, it might take a couple of days to fix. You can close the issue if you want, I'll create another one once it is fixed.

**Comment by theadeyemiolayinka** [comment]
@Money-20
Oh, no problem.
I'll leave the issue open till then. I hope your laptop gets fixed soon.
Cheers!

**Comment by Money-20** [comment]
I'll make a PR within 2 days mate. Thanks for waiting this long.

**Comment by theadeyemiolayinka** [comment]
@Money-20 No problem bro.
