### ISSUE TITLE
Python Hacktoberfest Contributions.

### ISSUE THREAD

**Issue by theadeyemiolayinka** [theadeyemiolayinka/python-scripts#65]
Feel free to add your python projects following the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)

**Comment by RAHULANUP** [comment]
Can I work on adding a bubble sort program in python

**Comment by RAHULANUP** [comment]
@theadeyemiolayinka thanks....
