### ISSUE TITLE
Menu driven code in python for celsius to fahrenheit and fahrenheit to celcius conversion

### ISSUE THREAD

**Issue by aishwarya0918** [theadeyemiolayinka/python-scripts#72]
Please assign me this issue

**Comment by theadeyemiolayinka** [comment]
@aishwarya0918 
Go ahead!

**Comment by aishwarya0918** [comment]
#81 
please find solution submitted as pull request.

**Comment by aishwarya0918** [comment]
#81 Celsius to Fahrenheit and Fahrenheit to Celsius conversion

**Comment by aishwarya0918** [comment]
#84 Celsius to Fahrenheit and Fahrenheit to Celsius conversion
