### ISSUE TITLE
python code to calculate simple interest

### ISSUE THREAD

**Issue by aishwarya0918** [theadeyemiolayinka/python-scripts#83]
Please assign this issue to me

**Comment by theadeyemiolayinka** [comment]
@aishwarya0918
Go ahead.

**Comment by aishwarya0918** [comment]
#86 Simple Interest calculation

**Comment by aishwarya0918** [comment]
#92 as i had not added the previous file in src folder ,i have corrected my mistake and added it in correct folder

**Comment by theadeyemiolayinka** [comment]
Okay.
Your PR had been merged.

**Comment by aishwarya0918** [comment]
Thank-you.
